//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int id { get; set; }
        public string Flight1 { get; set; }
        public string departure { get; set; }
        public string Destination { get; set; }
    }
}
